# Generated by Django 4.0.6 on 2023-05-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(max_length=30)),
                ('marks', models.TextField(max_length=5)),
            ],
        ),
    ]
